DROP DATABASE IF EXISTS httpstats_api;
CREATE DATABASE httpstats_api;
USE httpstats_api;
SET GLOBAL innodb_file_per_table=1;
SET GLOBAL innodb_file_format=Barracuda;
--SET GLOBAL innodb_compression_algorithm='lzma';
SET GLOBAL innodb_compression_level=9;
SET GLOBAL tx_isolation = 'READ-COMMITTED';
CREATE TABLE users                   ( id INT(11) NOT NULL,            username VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, UNIQUE KEY `id` (`id`), UNIQUE KEY `uusername` (`username`)) ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=16;
CREATE TABLE api_user_types          ( id INT NOT NULL AUTO_INCREMENT, name VARCHAR(255) NOT NULL,     UNIQUE KEY `id` (`id`),         UNIQUE KEY `name` (`name`)) ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=16;
CREATE TABLE api_users               ( id INT NOT NULL AUTO_INCREMENT, username VARCHAR(255) NOT NULL, password BLOB NOT NULL,         user_type_id INT NOT NULL, UNIQUE KEY `id` (`id`), KEY `user_type_id` (`user_type_id`), CONSTRAINT `fk_user_type_id` FOREIGN KEY (`user_type_id`) REFERENCES `user_types` (`id`), UNIQUE KEY `username` (`username`), UNIQUE KEY `user_and_type` (`username`, `user_type_id`)) ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=16;
CREATE TABLE api_actions             ( id INT NOT NULL AUTO_INCREMENT, name VARCHAR(255) NOT NULL,     UNIQUE KEY `id` (`id`),         UNIQUE KEY `name` (`name`)) ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=16;
CREATE TABLE api_rights_by_user_type ( id INT NOT NULL AUTO_INCREMENT, action_id INT NOT NULL,         user_type_id INT NOT NULL,      allowed TINYINT(1) NOT NULL, UNIQUE KEY `id` (`id`), KEY `user_type_id` (`user_type_id`), CONSTRAINT `fk_usertype_id` FOREIGN KEY (`user_type_id`) REFERENCES `user_types` (`id`), KEY `action_id` (`action_id`), CONSTRAINT `fk_action_id` FOREIGN KEY (`action_id`) REFERENCES `api_actions` (`id`), UNIQUE KEY `action_usertype` (`action_id`,`user_type_id`)) ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=16;
