DROP DATABASE IF EXISTS httpstats_jobs;
CREATE DATABASE httpstats_jobs;
USE httpstats_jobs;
SET GLOBAL innodb_file_per_table=1;
SET GLOBAL innodb_file_format=Barracuda;
SET GLOBAL innodb_compression_level=9;
SET GLOBAL tx_isolation = 'READ-COMMITTED';
CREATE TABLE stats_completed_ranges_hrs    ( id INT NOT NULL AUTO_INCREMENT, start_ts DATETIME NOT NULL, end_ts DATETIME NOT NULL, domains_id INT NOT NULL, UNIQUE KEY `id` (`id`), UNIQUE KEY `st_et` (`start_ts`, `end_ts`, `domains_id`)) ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=16;
CREATE TABLE stats_completed_ranges_days   ( id INT NOT NULL AUTO_INCREMENT, start_ts DATETIME NOT NULL, end_ts DATETIME NOT NULL, domains_id INT NOT NULL, UNIQUE KEY `id` (`id`), UNIQUE KEY `st_et` (`start_ts`, `end_ts`, `domains_id`)) ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=16;
CREATE TABLE stats_completed_ranges_weeks  ( id INT NOT NULL AUTO_INCREMENT, start_ts DATETIME NOT NULL, end_ts DATETIME NOT NULL, domains_id INT NOT NULL, UNIQUE KEY `id` (`id`), UNIQUE KEY `st_et` (`start_ts`, `end_ts`, `domains_id`)) ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=16;
CREATE TABLE stats_completed_ranges_months ( id INT NOT NULL AUTO_INCREMENT, start_ts DATETIME NOT NULL, end_ts DATETIME NOT NULL, domains_id INT NOT NULL, UNIQUE KEY `id` (`id`), UNIQUE KEY `st_et` (`start_ts`, `end_ts`, `domains_id`)) ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=16;
CREATE TABLE stats_completed_ranges_years  ( id INT NOT NULL AUTO_INCREMENT, start_ts DATETIME NOT NULL, end_ts DATETIME NOT NULL, domains_id INT NOT NULL, UNIQUE KEY `id` (`id`), UNIQUE KEY `st_et` (`start_ts`, `end_ts`, `domains_id`)) ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=16;
CREATE TABLE stats_completed_ranges_totals ( id INT NOT NULL AUTO_INCREMENT, start_ts DATETIME NOT NULL, end_ts DATETIME NOT NULL, domains_id INT NOT NULL, UNIQUE KEY `id` (`id`), UNIQUE KEY `st_et` (`start_ts`, `end_ts`, `domains_id`)) ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=16;
